### ISSUE TITLE
Parse CSV files for 2016 General Election

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-wa#3]
Washington state produces CSV files for the [2016 general](http://results.vote.wa.gov/results/20161108/Export.html). What we need are 2 CSV files, one for [this county-level results file](http://results.vote.wa.gov/results/20161108/export/20161108_AllCounties.csv) and another for [precinct-level results](http://results.vote.wa.gov/results/20161108/export/20161108_AllStatePrecincts.csv).

The headers for both files:

county: `county`, `office`, `district`, `party`, `candidate`, `votes`
precinct: `county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

You should include the following offices: President, U.S. Senate, U.S. House, Governor, Lt. Governor, Secretary of State, State Treasurer, State Auditor, Attorney General, Commissioner of Public Lands, Superintendent of Public Instruction, Insurance Commissioner, State Senate and State House.

For the `district` column, you'll need to ensure that State House races have both the district and the "position", so State House District 1 Position 1 would look like this: `1-1`. 

For the `party` column, you can replace "(Prefers {party name} Party)" with just {party name}.

Should you build a parser to do this, it would be ideal if it were generic enough to accept other elections, since recent Washington elections use the same formats.

**Comment by alistaire47** [comment]
I'll take this on! A couple questions/notes about the data:

- How far should I standardize parties? Cleaning cruft (`Party Nominees`, etc) is obvious, but should I lump `Republican`, `GOP`, `G.O.P` (no, there's not a third period here...) and similar? It's hard to predict what new data run through the parsing function will look like, though.
- In the `Prefers` variants, there's some bizarre ones that should probably be `NA`, e.g. `States No Party Preference`, `Prefers None Party`, `Prefers Non-Partisan Party` (nicely oxymoronic).
- The `Prefers` parties also mix `Independent` with actual parties, which seems weird and like it should be chopped.
- The precinct data doesn't have parties at all. Assuming candidates are formatted the same in both (a big ask, but the data is pretty good, as it goes) I'll try to append them with a join, but that will make reusing the scripts for multiple elections harder, as they'll always have to be parsed in parallel.
- The precinct data uses a county abbreviation instead of a full county name. I'll see if I can find a conversion table.
- The actual precincts are listed as both a name and a numeric code (not the precinct number; `Ritzville Ward #1` is code `111`). The name certainly seems more immediately useful, but the code could be kept too, either by appending it to names or leaving an extra column.

I've got a version sorted for the counties already, and I'll try to get a PR up within a day or so.

**Comment by dwillis** [comment]
@alistaire47 Thanks! Let's not worry about standardizing parties at this point, except for the obvious cruft. You can put `N/A` for the bizarre variants, too. Let's leave in `Independent` for now.

Let's try and match the parties for 2016 - is there a way to make the party-matching process an optional one? - and list the precinct code in a separate column called `precinct_code`.

It looks to me like the county codes in the precinct file are abbreviations for the counties (mostly first two letters, but sometimes not). Let me know if that's not the case or things seem unclear.
